### PR TITLE
[major] Bump NYC and Mocha to latest version

### PR DESCRIPTION
**Pull request by Zaky7**
Updated two packages for resolving the vulnerability

### nyc 
nyc updatd from v14.1.1 to v15.0.0 for resolving handlebars vulnerability

## mocha
mocha updated from v6.0.0 to v7.0.0 for resolving minimist vulnerability

### CODE REVIEW

**Comment by Zaky7** [comment]
@stjohnjohnson FYI

**Comment by brettz9** [comment]
Note that this fixes #42

**Comment by redonkulus** [comment]
@Zaky7 mocha just released 8.x, want to upgrade to that?

@stjohnjohnson want to give me access to merge and publish to npm???

**Comment by sozakir** [comment]
@redonkulus Mocha has significantly changed the API for version 8 with breaking changes. I think we should first merge version 7 in Jenkins-mocha, then you can create another PR for merging Version 8 of mocha.

**Comment by Zaky7** [comment]
@redonkulus Mocha has significantly changed the API for version 8 with breaking changes. I think we should first merge version 7 in Jenkins-mocha, then you can create another PR for merging Version 8 of mocha.

**Comment by avik-so** [comment]
> @redonkulus Mocha has significantly changed the API for version 8 with breaking changes. I think we should first merge version 7 in Jenkins-mocha, then you can create another PR for merging Version 8 of mocha.

I created a PR here: https://github.com/stjohnjohnson/jenkins-mocha/pull/44

**Comment by dskrvk** [comment]
It would be great to see this merged and published. What's blocking this?

**Comment by stjohnjohnson** [comment]
Sorry for the delay, published https://www.npmjs.com/package/jenkins-mocha/v/9.0.0

**Comment by stjohnjohnson** [comment]
Let me know if you have Mocha 8 and Mocha 9 PRs.  I'll try to review and publish quickly.

**Pull request merged**
