### PR TITLE
 add support for --no-coverage option to just run unit tests with mocha

### LINKED ISSUE #4: add option to disable coverage reporting
@stjohnjohnson 

It would be nice if we could pass a flag that would turn off coverage collection/reporting since we can't run mocha independently anymore.

### PR DESCRIPTION
**Pull request by koulmomo**
@stjohnjohnson 

resolves #4 
includes unit test + doc update

### CODE REVIEW

**Comment by koulmomo** [comment]
not sure why the PR build is failing.

**Comment by stjohnjohnson** [comment]
Arg, I'm testing out the beta Docker mode of werker.  Let me check it out.

**Comment by stjohnjohnson** [comment]
Okay, went back to normal Werker.  Works!  LGTM :+1:
permit_small

**Comment by stjohnjohnson** [comment]
Available in jenkins-mocha@2.2.0

**Pull request merged**
